name: Build and deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
      - uses: actions/checkout@master
      - name: Install dependencies
        run: yarn ci
      - name: Build dependencies
        run: yarn run build
  deploy:
     name: Deploy
     needs: build
     runs-on: ubuntu-latest
     steps:
          - name: Checkout repository
            uses: actions/checkout@master
            with:
              name: dist
              path: dist
          - name: Deploy to Firebase
            uses: w9jds/firebase-action@master
            with:
              args: deploy --only hosting
            env:
              FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_COMMENTO_D85F3 }}
            
            
   
