name: Build and deploy

on:
  push:
    branches:
      - master

  # Run workflow manually
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Install dependencies
        run: yarn --prefer-offline
      - name: Build dependencies
        run: yarn run build
      - name: Archive production artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
  deploy:
    uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.FIREBASE_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_COMMENTO_D85F3}}'
          channelId: live
          projectId: commento-d85f3
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
